### ISSUE TITLE
Get all country objects

### ISSUE THREAD

**Issue by joshbrw** [rinvex/country#60]
Any way of getting all countries as `Country` objects instead of an array?

**Comment by juanmiguel431** [comment]
Is there a way to get all the country list?

**Comment by Omranic** [comment]
@joshbrw Yep, `countries(false, true);` The second argument is a **hydrate** flag, that will return Country objects rather than plain array. Enjoy 😉 

@juanmiguel431 Sure, simply `countries()`. That's it 👍 
P.S. Alternative way is to use `Rinvex\Country\CountryLoader::countries();` no difference, it's purely up to you to use the helper or the fully qualified namespace.

Please don't hesitate to ask for further assistance, you can reach out via slack https://chat.rinvex.com too.
