### ISSUE TITLE
How can I keep the country JSON file updated ?  

### ISSUE THREAD

**Issue by gocanto** [rinvex/country#8]

**Comment by Omranic** [comment]
Sorry, I didn't get your question.
Could you please clarify it, what do you mean by keeping the JSON file updates?
`composer update rinvex/country` supposed to update the whole package including that countries.json file, and since country data rarely change, then it's less likely it's gonna be updated..

**Comment by gocanto** [comment]
I am sorry. What I meant was how can I keep the country.json file uptodate? Or how do you guys plan to do it? I saw that the countries info come form a static json file.

**Comment by Omranic** [comment]
I see, look it's as simple as running `composer update rinvex/country` command to update the package including that `country.json` static file. But here's the good news, a new migration & seed will be added soon to the package so you can control that from your DB/App side as well 👍 #7

**Comment by gocanto** [comment]
Cool, I see.. Just wanted to see how to depend of something online rather than a composer update. Anyways. I love this pkg. thanks tho
